// Generated by CoffeeScript 1.6.3
(function() {
  var WebFITS;

  if (this.astro == null) {
    this.astro = {};
  }

  WebFITS = {};

  WebFITS.version = '0.4.3';

  this.astro.WebFITS = WebFITS;

}).call(this);
